apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-eureka-server2
  namespace: spring-cloud
  labels:
    app: spring-cloud-eureka-server2
spec:
  ports:
  - port: 8761
    name: http
  selector:
    app: spring-cloud-eureka-server2
  type: NodePort
  externalIPs:
  - 192.168.237.162
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-eureka-server2
  namespace: spring-cloud
spec:
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: spring-cloud-eureka-server2
    spec:
      volumes:
      - name : log-path
        hostPath:
          path: /home/k8s/data/eureka-server2/logs
      containers:
      - name: spring-cloud-eureka-server
        image: sky01126/spring-cloud-eureka-server:1.0.0.RELEASE
        env:
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -Dserver.port=8761 -Dfile.encoding=UTF8 -Dclient.encoding.override=UTF-8 -Duser.timezone=GMT+09:00 -Dsun.java2d.opengl=false -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dspring.profiles.active=prod -Dlog.home=/home/logs -Dconfig.server.host=spring-cloud-config-server.spring-cloud -Dconfig.server.port=8888 -Ddocker.host.server.address=192.168.237.162 -Deureka.peer.name=spring-cloud-eureka-server2 -Deureka.client.default.zone=spring-cloud-eureka-server1.spring-cloud"
        args: ["$(JAVA_OPTS)"]
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: log-path
          mountPath: /home/logs
