apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-msa-webapp01
  namespace: spring-cloud
spec:
  replicas: 2
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: spring-cloud-msa-webapp01
    spec:
      volumes:
      - name : log-path
        hostPath:
          path: /home/k8s/data/msa-server/logs
      containers:
      - name: spring-cloud-msa-webapp01
        image: sky01126/spring-cloud-msa-webapp01:1.0.0.RELEASE
        env:
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -Xms128m -Dserver.port=18081 -Dfile.encoding=UTF8 -Dclient.encoding.override=UTF-8 -Duser.timezone=GMT+09:00 -Dsun.java2d.opengl=false -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dspring.profiles.active=prod -Dlogs.home=/home/logs -Dconfig.server.host=spring-cloud-config-server.spring-cloud -Dconfig.server.port=8888"
        args: ["$(JAVA_OPTS)"]
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 18081
        volumeMounts:
        - name: log-path
          mountPath: /home/logs