apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-config-server
  namespace: spring-cloud
  labels:
    app: spring-cloud-config-server
spec:
  ports:
  - port: 8888
    name: http
  selector:
    app: spring-cloud-config-server
  type: NodePort
  externalIPs:
  - 172.16.109.151
  - 172.16.109.152
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-config-server
  namespace: spring-cloud
spec:
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: spring-cloud-config-server
    spec:
      volumes:
      - name : log-path
        hostPath:
          path: /home/k8s/data/config-server/logs
      containers:
      - name: spring-cloud-config-server
        image: sky01126/spring-cloud-config-server:1.0.0.RELEASE
        env:
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -Dserver.port=8888 -Dfile.encoding=UTF8 -Dclient.encoding.override=UTF-8 -Duser.timezone=GMT+09:00 -Dsun.java2d.opengl=false -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dspring.profiles.active=prod -Dlog.home=/home/logs"
        args: ["$(JAVA_OPTS)"]
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: log-path
          mountPath: /home/logs
