apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-config-server
  namespace: spring-cloud
  labels:
    app: spring-cloud-config-server
spec:
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    app: spring-cloud-config-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-config-server
  namespace: spring-cloud
spec:
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: spring-cloud-config-server
    spec:
      volumes:
      - name : logs-path
        hostPath:
         path: /nasdata/ocdata/spring-cloud/config/logs
      containers:
      - name: spring-cloud-config-server
        image: sky01126/spring-cloud-config-server:1.0.0.RELEASE
        env:
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -Xms128m -Dserver.port=8888 -Dfile.encoding=UTF8 -Dclient.encoding.override=UTF-8 -Duser.timezone=GMT+09:00 -Dsun.java2d.opengl=false -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dspring.profiles.active=prod -Dlogs.home=/home/server/logs"
        args: ["$(JAVA_OPTS)"]
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: logs-path
          mountPath: /home/server/logs