apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-eureka-server2
  namespace: spring-cloud
  labels:
    app: spring-cloud-eureka-server2
spec:
  ports:
  - name: http
    port: 8761
    targetPort: 8761
  selector:
    app: spring-cloud-eureka-server2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-eureka-server2
  namespace: spring-cloud
spec:
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: spring-cloud-eureka-server2
    spec:
      volumes:
      - name : logs-path
        hostPath:
         path: /nasdata/ocdata/spring-cloud/eureka02/logs
      containers:
      - name: spring-cloud-eureka-server
        image: sky01126/spring-cloud-eureka-server:1.0.1.RELEASE
        env:
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -Xms128m -Dserver.port=8761 -Dfile.encoding=UTF8 -Dclient.encoding.override=UTF-8 -Duser.timezone=GMT+09:00 -Dsun.java2d.opengl=false -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dspring.profiles.active=prod -Dlogs.home=/home/server/logs -Dconfig.server.host=spring-cloud-config-server.spring-cloud -Dconfig.server.port=8888 -Deureka.peer.name=spring-cloud-eureka-server2 -Deureka.cluster.peer.url=spring-cloud-eureka-server1.spring-cloud"
        args: ["$(JAVA_OPTS)"]
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: logs-path
          mountPath: /home/server/logs